/* automatically generated by rust-bindgen 0.57.0 */

pub type __int64_t = ::std::os::raw::c_long;
pub type gint_t = i64;
pub type dim_t = gint_t;
extern "C" {
    pub fn bli_thread_set_num_threads(value: dim_t);
}
